#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFactory.Views.Shared.FormFactory
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\FormFactory\Property.IEnumerable.System.Object.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/FormFactory/Property.IEnumerable.System.Object.cshtml")]
    public class Property_IEnumerable_System_Object : System.Web.Mvc.WebViewPage<PropertyVm>
    {
        public Property_IEnumerable_System_Object()
        {
        }
        public override void Execute()
        {


WriteLiteral("<ul>\r\n");


            
            #line 4 "..\..\Views\Shared\FormFactory\Property.IEnumerable.System.Object.cshtml"
      
        var i = 0;

        foreach (var obj in (IEnumerable<object>)Model.Value)
        {

            
            #line default
            #line hidden
WriteLiteral("        <li>\r\n");


            
            #line 10 "..\..\Views\Shared\FormFactory\Property.IEnumerable.System.Object.cshtml"
              
            var prop = new PropertyVm(Html, obj.GetType(), Model.Name + i)
            {
                Value = obj
            };
                
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\FormFactory\Property.IEnumerable.System.Object.cshtml"
           Write(Html.BestProperty(prop));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\FormFactory\Property.IEnumerable.System.Object.cshtml"
                                        
            

            
            #line default
            #line hidden
WriteLiteral("        </li>\r\n");


            
            #line 18 "..\..\Views\Shared\FormFactory\Property.IEnumerable.System.Object.cshtml"
        }
    

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n");


        }
    }
}
#pragma warning restore 1591
