#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFactory.Views.Shared.FormFactory
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/FormFactory/Property.System.String.cshtml")]
    public class Property_System_String : System.Web.Mvc.WebViewPage<PropertyVm>
    {
        public Property_System_String()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
 if (Model.IsWritable && Model.Choices != null)
{
    var choices = Model.Choices as IEnumerable<Tuple<string, string>>;
    if (choices == null && Model.Choices is IEnumerable<string>)
    {
        choices = Model.Choices.Cast<string>().Select(c => Tuple.Create(c, c));
    }

            
            #line default
            #line hidden
WriteLiteral("    <select name=\"");


            
            #line 11 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
             Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" id=\"");


            
            #line 11 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                              Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"");


            
            #line 11 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                                                   Write(Model.IsWritable ? "" : "disabled");

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 11 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                                                                                          Write(Model.IsWritable ? "" : "disabled=disabled");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");


            
            #line 12 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
         foreach (var option in choices)
        {

            
            #line default
            #line hidden
WriteLiteral("            <option value=\"");


            
            #line 14 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                      Write(option.Item2);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 14 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                                     Write(option.Item1);

            
            #line default
            #line hidden
WriteLiteral("</option>    \r\n");


            
            #line 15 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </select>\r\n");


            
            #line 17 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
}
else
{
    var dataAttributes = Model.GetCustomAttributes().OfType<DataTypeAttribute>();
    var inputType = dataAttributes.Any(da => da.DataType == DataType.Password) ? "password" : "text";

    if (!Model.IsWritable)
    {

            
            #line default
            #line hidden
WriteLiteral("        <span class=\"xlarge uneditable-input\" >");


            
            #line 25 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                                          Write(Model.Value);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 26 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <input class=\"xlarge\" id=\"");


            
            #line 29 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                             Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");


            
            #line 29 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                                                Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" size=\"30\" type=\"");


            
            #line 29 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                                                                             Write(inputType);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");


            
            #line 29 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                                                                                                Write(Model.Value);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 30 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"

        if (Model.Suggestions != null && Model.Suggestions.Cast<object>().Any())
        {
            var escapedSuggestions = Model.Suggestions.Cast<string>().Select(s => s.Replace("'", "''"));

            
            #line default
            #line hidden
WriteLiteral(@"            <script type=""text/javascript"">
                $(function () {
                    if (jQuery().autocomplete) {
                        window.setTimeout(function () { //in a timeout so it can be embedded in a popover
                            $(""#");


            
            #line 38 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                           Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\")\r\n                                .autocomplete({\r\n                            " +
"        source: [\'");


            
            #line 40 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                                         Write(Html.Raw(string.Join("', '", escapedSuggestions)));

            
            #line default
            #line hidden
WriteLiteral(@"'],
                                    minLength: 0
                                })
                                .focus(function () {
                                    $(this).trigger('keydown.autocomplete');
                                });
                        }, 1);
                    } else {
                        console.log(""could not load $.autocomplete for ");


            
            #line 48 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
                                                                  Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" suggestions\");\r\n                    }\r\n                });\r\n    </script>\r\n");


            
            #line 52 "..\..\Views\Shared\FormFactory\Property.System.String.cshtml"
        }
    }
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
