using System.Web.WebPages;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFactory.AspMvc.Example.Views.Home
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [PageVirtualPath("~/Views/Home/Test.cshtml")]
    public partial class _Views_Home_Test_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Test_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<h2>Test precompiled view</h2>\r\n<p>\r\n     This view needs to have its CustomTool " +
"set to RazorGenerator\r\n</p>\r\n");

        }
    }
}
#pragma warning restore 1591
