#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFactory.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Form.Property.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Form.Property.cshtml")]
    public class Form_Property : System.Web.Mvc.WebViewPage<PropertyVm>
    {
        public Form_Property()
        {
        }
        public override void Execute()
        {


WriteLiteral("<div class=\"clearfix ");


            
            #line 3 "..\..\Views\Shared\Form.Property.cshtml"
                 Write(Html.HasErrors(Model.Name) ? "error" : "");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <label for=\"");


            
            #line 4 "..\..\Views\Shared\Form.Property.cshtml"
           Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 4 "..\..\Views\Shared\Form.Property.cshtml"
                        Write(Model.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n    <div class=\"input ");


            
            #line 5 "..\..\Views\Shared\Form.Property.cshtml"
                  Write(Html.HasErrors(Model.Name) ? "error" : "");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        ");


            
            #line 6 "..\..\Views\Shared\Form.Property.cshtml"
   Write(Html.BestProperty(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <span class=\"help-inline\">");


            
            #line 7 "..\..\Views\Shared\Form.Property.cshtml"
                             Write(Html.AllValidationMessages(Model.Name));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
