#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFactory.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Form.Start.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Form.Start.cshtml")]
    public class Form_Start : System.Web.Mvc.WebViewPage<FormVm>
    {
        public Form_Start()
        {
        }
        public override void Execute()
        {


WriteLiteral("<div class=\"row\">\r\n\r\n");


            
            #line 5 "..\..\Views\Shared\Form.Start.cshtml"
  if (Model.SideMessage == null)
 {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral("\r\n    <div class=\"span16\">     \r\n    ");

WriteLiteral("\r\n");


            
            #line 10 "..\..\Views\Shared\Form.Start.cshtml"
 }
 else
 {

            
            #line default
            #line hidden
WriteLiteral("     ");

WriteLiteral("\r\n    <div class=\"span4\">\r\n        <p>\r\n            ");


            
            #line 16 "..\..\Views\Shared\Form.Start.cshtml"
       Write(Model.SideMessage);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n    </div>\r\n    <div class=\"span12\">\r\n    ");

WriteLiteral("\r\n");


            
            #line 21 "..\..\Views\Shared\Form.Start.cshtml"
}        

            
            #line default
            #line hidden
WriteLiteral("            \r\n");


            
            #line 23 "..\..\Views\Shared\Form.Start.cshtml"
 if (!ViewData.ModelState.IsValid)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"alert-message block-message error\">\r\n        Sorry, there were so" +
"me problems. Please correct them and try again.<br />\r\n        ");


            
            #line 27 "..\..\Views\Shared\Form.Start.cshtml"
   Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");


            
            #line 29 "..\..\Views\Shared\Form.Start.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<form action=\"");


            
            #line 30 "..\..\Views\Shared\Form.Start.cshtml"
         Write(Model.ActionUrl);

            
            #line default
            #line hidden
WriteLiteral("\" method=\"POST\">\r\n    <fieldset>\r\n");


        }
    }
}
#pragma warning restore 1591
