#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFactory.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Property.System.Boolean.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Property.System.Boolean.cshtml")]
    public class Property_System_Boolean : System.Web.Mvc.WebViewPage<PropertyVm>
    {
        public Property_System_Boolean()
        {
        }
        public override void Execute()
        {


WriteLiteral("           \r\n");


            
            #line 4 "..\..\Views\Shared\Property.System.Boolean.cshtml"
   var value = Model.Value as bool? ?? false;


            
            #line default
            #line hidden
WriteLiteral("<input type=\'hidden\' value=\'");


            
            #line 6 "..\..\Views\Shared\Property.System.Boolean.cshtml"
                       Write(value.ToString().ToLower());

            
            #line default
            #line hidden
WriteLiteral("\' id=\"");


            
            #line 6 "..\..\Views\Shared\Property.System.Boolean.cshtml"
                                                        Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" name=\'");


            
            #line 6 "..\..\Views\Shared\Property.System.Boolean.cshtml"
                                                                           Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\'>\r\n<input class=\"");


            
            #line 7 "..\..\Views\Shared\Property.System.Boolean.cshtml"
          Write(Model.IsWritable ? "" : "disabled");

            
            #line default
            #line hidden
WriteLiteral("\" type=\"checkbox\" value=\"true\" ");


            
            #line 7 "..\..\Views\Shared\Property.System.Boolean.cshtml"
                                                                              Write(value ? "checked=checked" : "");

            
            #line default
            #line hidden
WriteLiteral(" onchange=\"javascript: $(\'#");


            
            #line 7 "..\..\Views\Shared\Property.System.Boolean.cshtml"
                                                                                                                                         Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\').val($(this).is(\':checked\'))\" ");


            
            #line 7 "..\..\Views\Shared\Property.System.Boolean.cshtml"
                                                                                                                                                                                     Write(Model.IsWritable ? "" : "disabled=\"disabled\"");

            
            #line default
            #line hidden
WriteLiteral("/>\r\n");


        }
    }
}
#pragma warning restore 1591
