#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFactory.Views.Shared
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Shared\Property.System.String.cshtml"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\Property.System.String.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Property.System.String.cshtml")]
    public class Property_System_String : System.Web.Mvc.WebViewPage<PropertyVm>
    {
        public Property_System_String()
        {
        }
        public override void Execute()
        {




            
            #line 4 "..\..\Views\Shared\Property.System.String.cshtml"
 if (Model.Choices != null)
{
    var choices = Model.Choices.Cast<string>();

            
            #line default
            #line hidden
WriteLiteral("    <select name=\"");


            
            #line 7 "..\..\Views\Shared\Property.System.String.cshtml"
             Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" id=\"");


            
            #line 7 "..\..\Views\Shared\Property.System.String.cshtml"
                              Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"");


            
            #line 7 "..\..\Views\Shared\Property.System.String.cshtml"
                                                   Write(Model.IsWritable ? "" : "disabled");

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 7 "..\..\Views\Shared\Property.System.String.cshtml"
                                                                                          Write(Model.IsWritable ? "" : "disabled=disabled");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");


            
            #line 8 "..\..\Views\Shared\Property.System.String.cshtml"
         foreach (var option in choices)
        {

            
            #line default
            #line hidden
WriteLiteral("            <option value=\"");


            
            #line 10 "..\..\Views\Shared\Property.System.String.cshtml"
                      Write(option);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 10 "..\..\Views\Shared\Property.System.String.cshtml"
                               Write(option);

            
            #line default
            #line hidden
WriteLiteral("</option>    \r\n");


            
            #line 11 "..\..\Views\Shared\Property.System.String.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </select>\r\n");


            
            #line 13 "..\..\Views\Shared\Property.System.String.cshtml"
}
else
{
    var dataAttributes = Model.GetCustomAttributes().OfType<DataTypeAttribute>();
    var inputType = dataAttributes.Any(da => da.DataType == DataType.Password) ? "password" : "text";



            
            #line default
            #line hidden
WriteLiteral("    <input class=\"xlarge ");


            
            #line 20 "..\..\Views\Shared\Property.System.String.cshtml"
                     Write(Model.IsWritable ? "" : "disabled");

            
            #line default
            #line hidden
WriteLiteral("\" id=\"");


            
            #line 20 "..\..\Views\Shared\Property.System.String.cshtml"
                                                               Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"");


            
            #line 20 "..\..\Views\Shared\Property.System.String.cshtml"
                                                                                  Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" size=\"30\" type=\"");


            
            #line 20 "..\..\Views\Shared\Property.System.String.cshtml"
                                                                                                               Write(inputType);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");


            
            #line 20 "..\..\Views\Shared\Property.System.String.cshtml"
                                                                                                                                  Write(Model.Value);

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 20 "..\..\Views\Shared\Property.System.String.cshtml"
                                                                                                                                                 Write(Model.IsWritable ? "" : "disabled=\"disabled\"");

            
            #line default
            #line hidden
WriteLiteral("/>\r\n");


            
            #line 21 "..\..\Views\Shared\Property.System.String.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
