#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.468
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFactory.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\Property.System.Enum.cshtml"
    using FormFactory;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Property.System.Enum.cshtml")]
    public class Property_System_Enum : System.Web.Mvc.WebViewPage<PropertyVm>
    {
        public Property_System_Enum()
        {
        }
        public override void Execute()
        {


WriteLiteral("           \r\n");


            
            #line 4 "..\..\Views\Shared\Property.System.Enum.cshtml"
  
    var enumType = Model.Value.GetType();
    var displayValue = Enum.Parse(enumType, Model.Value.ToString());
 

            
            #line default
            #line hidden
WriteLiteral("<select name=\"");


            
            #line 8 "..\..\Views\Shared\Property.System.Enum.cshtml"
         Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 8 "..\..\Views\Shared\Property.System.Enum.cshtml"
                       Write(Model.IsWritable ? "" : "disabled=disabled");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");


            
            #line 9 "..\..\Views\Shared\Property.System.Enum.cshtml"
     foreach (var enumMember in Enum.GetValues(enumType))
    {
        var selected = (displayValue == enumMember);

            
            #line default
            #line hidden
WriteLiteral("        <option value=\"");


            
            #line 12 "..\..\Views\Shared\Property.System.Enum.cshtml"
                  Write(enumMember.ToString());

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 12 "..\..\Views\Shared\Property.System.Enum.cshtml"
                                           Write(selected ? "selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 12 "..\..\Views\Shared\Property.System.Enum.cshtml"
                                                                                 Write(enumMember.ToString().Sentencise());

            
            #line default
            #line hidden
WriteLiteral("</option>    \r\n");


            
            #line 13 "..\..\Views\Shared\Property.System.Enum.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</select>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
